[build]
    functions="functions"

[[redirects]]
    from="/*"
    to="/.netlify/functions/server"
    status=200
    force=true
[build.environment]
  MY_SECRET_KEY = "some_secret_value"
  API_URL = "https://api.example.com"